-- 20260916120000_service_orders.sql
CREATE TABLE public.service_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  org_id uuid NOT NULL DEFAULT public.current_org_id()
    REFERENCES public.organizations(id) ON DELETE RESTRICT,
  client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE RESTRICT,
  service_id uuid REFERENCES public.services(id) ON DELETE SET NULL,
  title text NOT NULL CHECK (length(btrim(title)) > 0),
  description text,
  status text NOT NULL DEFAULT 'requested' CHECK (status IN (
    'requested', 'waiting_documents', 'preparing', 'submitted',
    'waiting_agency', 'approved', 'delivered', 'cancelled'
  )),
  priority text NOT NULL DEFAULT 'normal'
    CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  assigned_to uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  due_date date,
  sla_hours integer CHECK (sla_hours IS NULL OR sla_hours > 0),
  quoted_amount numeric(12, 2) NOT NULL DEFAULT 0 CHECK (quoted_amount >= 0),
  external_cost numeric(12, 2) NOT NULL DEFAULT 0 CHECK (external_cost >= 0),
  currency text NOT NULL DEFAULT 'USD' CHECK (currency IN ('USD', 'BRL')),
  started_at timestamptz,
  submitted_at timestamptz,
  approved_at timestamptz,
  completed_at timestamptz,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX service_orders_org_status_idx ON public.service_orders(org_id, status);
CREATE INDEX service_orders_client_idx ON public.service_orders(client_id, created_at DESC);
CREATE INDEX service_orders_assigned_idx ON public.service_orders(assigned_to, status)
  WHERE assigned_to IS NOT NULL;
CREATE INDEX service_orders_due_idx ON public.service_orders(org_id, due_date)
  WHERE due_date IS NOT NULL AND status NOT IN ('delivered', 'cancelled');

CREATE TABLE public.service_order_permits (
  service_order_id uuid NOT NULL REFERENCES public.service_orders(id) ON DELETE CASCADE,
  permit_id uuid NOT NULL REFERENCES public.permits(id) ON DELETE RESTRICT,
  org_id uuid NOT NULL DEFAULT public.current_org_id()
    REFERENCES public.organizations(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (service_order_id, permit_id)
);

CREATE INDEX service_order_permits_permit_idx ON public.service_order_permits(permit_id);
CREATE INDEX service_order_permits_org_idx ON public.service_order_permits(org_id);

CREATE TABLE public.service_order_checklist_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  service_order_id uuid NOT NULL REFERENCES public.service_orders(id) ON DELETE CASCADE,
  org_id uuid NOT NULL DEFAULT public.current_org_id()
    REFERENCES public.organizations(id) ON DELETE RESTRICT,
  title text NOT NULL CHECK (length(btrim(title)) > 0),
  description text,
  document_type text,
  required boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'received', 'approved', 'rejected', 'not_applicable'
  )),
  document_path text,
  file_name text,
  rejection_reason text,
  due_date date,
  sort_order integer NOT NULL DEFAULT 0,
  completed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  completed_at timestamptz,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX service_order_checklist_order_idx
  ON public.service_order_checklist_items(service_order_id, sort_order, created_at);
CREATE INDEX service_order_checklist_org_status_idx
  ON public.service_order_checklist_items(org_id, status);

CREATE TABLE public.service_order_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  service_order_id uuid NOT NULL REFERENCES public.service_orders(id) ON DELETE CASCADE,
  org_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  event_type text NOT NULL CHECK (event_type IN (
    'created', 'status_changed', 'assignment_changed', 'due_date_changed',
    'checklist_changed', 'permit_linked', 'permit_unlinked', 'note'
  )),
  from_value text,
  to_value text,
  note text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX service_order_events_order_idx
  ON public.service_order_events(service_order_id, created_at DESC);
CREATE INDEX service_order_events_org_idx ON public.service_order_events(org_id);

ALTER TABLE public.tasks
  ADD COLUMN service_order_id uuid REFERENCES public.service_orders(id) ON DELETE SET NULL;

CREATE INDEX tasks_service_order_idx ON public.tasks(service_order_id)
  WHERE service_order_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.validate_service_order_scope()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.clients c
    WHERE c.id = NEW.client_id AND c.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'client must belong to the service order organization';
  END IF;

  IF NEW.service_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.services s
    WHERE s.id = NEW.service_id AND s.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'service must belong to the service order organization';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER validate_service_order_scope_trigger
  BEFORE INSERT OR UPDATE OF org_id, client_id, service_id ON public.service_orders
  FOR EACH ROW EXECUTE FUNCTION public.validate_service_order_scope();

CREATE OR REPLACE FUNCTION public.validate_service_order_child_scope()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  order_org uuid;
BEGIN
  SELECT org_id INTO order_org
  FROM public.service_orders
  WHERE id = NEW.service_order_id;

  IF order_org IS NULL OR order_org <> NEW.org_id THEN
    RAISE EXCEPTION 'service order child must belong to the order organization';
  END IF;

  IF TG_TABLE_NAME = 'service_order_permits' AND NOT EXISTS (
    SELECT 1 FROM public.permits p
    WHERE p.id = NEW.permit_id AND p.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION 'permit must belong to the service order organization';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER validate_service_order_permit_scope_trigger
  BEFORE INSERT OR UPDATE ON public.service_order_permits
  FOR EACH ROW EXECUTE FUNCTION public.validate_service_order_child_scope();

CREATE TRIGGER validate_service_order_checklist_scope_trigger
  BEFORE INSERT OR UPDATE OF org_id, service_order_id ON public.service_order_checklist_items
  FOR EACH ROW EXECUTE FUNCTION public.validate_service_order_child_scope();

CREATE OR REPLACE FUNCTION public.validate_task_service_order_scope()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.service_order_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.service_orders so
    WHERE so.id = NEW.service_order_id
      AND so.org_id = NEW.org_id
      AND (NEW.client_id IS NULL OR so.client_id = NEW.client_id)
  ) THEN
    RAISE EXCEPTION 'task must belong to the service order organization and client';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER validate_task_service_order_scope_trigger
  BEFORE INSERT OR UPDATE OF org_id, client_id, service_order_id ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.validate_task_service_order_scope();

CREATE OR REPLACE FUNCTION public.apply_service_order_milestones()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status = 'preparing' AND NEW.started_at IS NULL THEN
      NEW.started_at := now();
    ELSIF NEW.status = 'submitted' AND NEW.submitted_at IS NULL THEN
      NEW.submitted_at := now();
    ELSIF NEW.status = 'approved' AND NEW.approved_at IS NULL THEN
      NEW.approved_at := now();
    ELSIF NEW.status = 'delivered' AND NEW.completed_at IS NULL THEN
      NEW.completed_at := now();
    ELSIF OLD.status = 'delivered' AND NEW.status <> 'delivered' THEN
      NEW.completed_at := NULL;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER apply_service_order_milestones_trigger
  BEFORE UPDATE OF status ON public.service_orders
  FOR EACH ROW EXECUTE FUNCTION public.apply_service_order_milestones();

CREATE TRIGGER update_service_orders_updated_at
  BEFORE UPDATE ON public.service_orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_service_order_checklist_updated_at
  BEFORE UPDATE ON public.service_order_checklist_items
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.log_service_order_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.service_order_events (
      service_order_id, org_id, event_type, to_value, actor_id, metadata
    ) VALUES (
      NEW.id, NEW.org_id, 'created', NEW.status, auth.uid(),
      jsonb_build_object('title', NEW.title)
    );
    RETURN NEW;
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.service_order_events (
      service_order_id, org_id, event_type, from_value, to_value, actor_id
    ) VALUES (NEW.id, NEW.org_id, 'status_changed', OLD.status, NEW.status, auth.uid());
  END IF;

  IF NEW.assigned_to IS DISTINCT FROM OLD.assigned_to THEN
    INSERT INTO public.service_order_events (
      service_order_id, org_id, event_type, from_value, to_value, actor_id
    ) VALUES (
      NEW.id, NEW.org_id, 'assignment_changed',
      OLD.assigned_to::text, NEW.assigned_to::text, auth.uid()
    );
  END IF;

  IF NEW.due_date IS DISTINCT FROM OLD.due_date THEN
    INSERT INTO public.service_order_events (
      service_order_id, org_id, event_type, from_value, to_value, actor_id
    ) VALUES (
      NEW.id, NEW.org_id, 'due_date_changed',
      OLD.due_date::text, NEW.due_date::text, auth.uid()
    );
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER log_service_order_event_trigger
  AFTER INSERT OR UPDATE ON public.service_orders
  FOR EACH ROW EXECUTE FUNCTION public.log_service_order_event();

CREATE OR REPLACE FUNCTION public.log_service_order_child_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  order_id uuid;
  order_org uuid;
BEGIN
  order_id := COALESCE(NEW.service_order_id, OLD.service_order_id);
  order_org := COALESCE(NEW.org_id, OLD.org_id);

  IF TG_TABLE_NAME = 'service_order_checklist_items' THEN
    IF TG_OP = 'INSERT' OR NEW.status IS DISTINCT FROM OLD.status
       OR NEW.document_path IS DISTINCT FROM OLD.document_path THEN
      INSERT INTO public.service_order_events (
        service_order_id, org_id, event_type, from_value, to_value,
        actor_id, metadata
      ) VALUES (
        order_id, order_org, 'checklist_changed',
        CASE WHEN TG_OP = 'UPDATE' THEN OLD.status ELSE NULL END,
        NEW.status, auth.uid(),
        jsonb_build_object('item_id', NEW.id, 'title', NEW.title, 'operation', lower(TG_OP))
      );
    END IF;
  ELSIF TG_TABLE_NAME = 'service_order_permits' THEN
    INSERT INTO public.service_order_events (
      service_order_id, org_id, event_type, actor_id, metadata
    ) VALUES (
      order_id, order_org,
      CASE WHEN TG_OP = 'DELETE' THEN 'permit_unlinked' ELSE 'permit_linked' END,
      auth.uid(), jsonb_build_object('permit_id', COALESCE(NEW.permit_id, OLD.permit_id))
    );
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER log_service_order_checklist_event_trigger
  AFTER INSERT OR UPDATE ON public.service_order_checklist_items
  FOR EACH ROW EXECUTE FUNCTION public.log_service_order_child_event();

CREATE TRIGGER log_service_order_permit_event_trigger
  AFTER INSERT OR DELETE ON public.service_order_permits
  FOR EACH ROW EXECUTE FUNCTION public.log_service_order_child_event();

ALTER TABLE public.service_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_order_permits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_order_checklist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_order_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org members read service orders"
  ON public.service_orders FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
CREATE POLICY "org writers create service orders"
  ON public.service_orders FOR INSERT TO authenticated
  WITH CHECK (public.can_org_write(org_id) AND created_by = auth.uid());
CREATE POLICY "org writers update service orders"
  ON public.service_orders FOR UPDATE TO authenticated
  USING (public.can_org_write(org_id)) WITH CHECK (public.can_org_write(org_id));
CREATE POLICY "org writers delete service orders"
  ON public.service_orders FOR DELETE TO authenticated
  USING (public.can_org_write(org_id));

CREATE POLICY "org members read service order permits"
  ON public.service_order_permits FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
CREATE POLICY "org writers create service order permits"
  ON public.service_order_permits FOR INSERT TO authenticated
  WITH CHECK (public.can_org_write(org_id));
CREATE POLICY "org writers delete service order permits"
  ON public.service_order_permits FOR DELETE TO authenticated
  USING (public.can_org_write(org_id));

CREATE POLICY "org members read service order checklist"
  ON public.service_order_checklist_items FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
CREATE POLICY "org writers create service order checklist"
  ON public.service_order_checklist_items FOR INSERT TO authenticated
  WITH CHECK (public.can_org_write(org_id) AND created_by = auth.uid());
CREATE POLICY "org writers update service order checklist"
  ON public.service_order_checklist_items FOR UPDATE TO authenticated
  USING (public.can_org_write(org_id)) WITH CHECK (public.can_org_write(org_id));
CREATE POLICY "org writers delete service order checklist"
  ON public.service_order_checklist_items FOR DELETE TO authenticated
  USING (public.can_org_write(org_id));

CREATE POLICY "org members read service order events"
  ON public.service_order_events FOR SELECT TO authenticated
  USING (public.is_org_member(org_id));
CREATE POLICY "org writers add service order notes"
  ON public.service_order_events FOR INSERT TO authenticated
  WITH CHECK (
    public.can_org_write(org_id)
    AND actor_id = auth.uid()
    AND event_type = 'note'
    AND EXISTS (
      SELECT 1 FROM public.service_orders so
      WHERE so.id = service_order_id AND so.org_id = org_id
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.service_orders TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.service_order_permits TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.service_order_checklist_items TO authenticated;
GRANT SELECT, INSERT ON public.service_order_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.service_orders_order_number_seq TO authenticated;

GRANT ALL ON public.service_orders TO service_role;
GRANT ALL ON public.service_order_permits TO service_role;
GRANT ALL ON public.service_order_checklist_items TO service_role;
GRANT ALL ON public.service_order_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.service_orders_order_number_seq TO service_role;

COMMENT ON TABLE public.service_orders IS
  'Client work cases with workflow, SLA, ownership and financial summary.';
COMMENT ON TABLE public.service_order_events IS
  'Append-only history generated by database triggers plus user notes.';